services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5170:5170"
    networks:
      - task-network
    environment:
      - ASPNETCORE_URLS=http://+:5170

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
